### ISSUE TITLE
Unable to reconnect

### ISSUE THREAD

**Issue by motoom** [Lawouach/WebSocket-for-Python#207] opened 2017-01-26 09:21 UTC
I run a chat service with CherryPy and ws4py. The client runs in a webbrowser and is very similar to the chat example from ws4py. When the client notices that the connection has been disconnected (this can happen easily, for example, due to an unstable Wifi connection), I try to re-establish the connection to the server. This somehow doesn't work. Am I trying to do something that is unsupported, or should it indeed be possible to reconnect a closed-down websocket? In the first case, I must find an alternative to ws4py, in the second case, I can prepare a minimal code example which demonstrates the behaviour.

**Comment by adippel** [comment] 2017-02-08 19:29
I faced the same task recently. AFAIK, ws4py does not provide a reconnect functionality. You have to implement it on your own by subclassing. However, simply calling `connect()` again might throw some errors especially when using encrypted connections. You have to make sure, that the previous connection is closed completely on the client-side before trying to call `connect()` again.
Have a look at this example I found: https://github.com/belisarius222/ws4py-reconnect/blob/master/wsclient.py

**Comment by EternityForest** [comment] 2017-03-24 03:34
Is this related at all to issue #150 where an abrupt disconnection will crash the server?

**Comment by adippel** [comment] 2017-03-24 08:34
AFAICS, your issue relates to problems on the server side. This issue, though, deals with a reconnection logic on the client side.
I referred to an example in my lost post. However, it seems like this example leads to a memory leak since it instantiates a new object on every reconnection try. 
The threaded client is hard to extend since a lot of setup and priming is done in the underlying constructors. I came up with a solution without creation of a new instance on every reconnect try. The solution is working okish but is rather hacky as it tries to mimic the setup and priming in the Subclasses of the threaded client.
You can find my minimal working example here: https://gist.github.com/adippel/a417d95d8401c09c158bac3c7ba92f07

**Comment by tito** [comment] 2017-03-24 13:55
Duplicate of #150 
This has been fixed in master, and will be released soon.

**Closed by tito** 2017-03-24 13:55 UTC
