### ISSUE TITLE
Python 3.4 and gevent 1.1

### ISSUE THREAD

**Issue by kolis** [Lawouach/WebSocket-for-Python#170] opened 2015-08-11 14:27 UTC
I'm testing the new gevent 1.1b2 which now support Python3. But the included gevent example https://ws4py.readthedocs.org/en/latest/sources/servertutorial/#gevent

gives crash on Mac OS X 10.10

```
Failed to receive data
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/ws4py/websocket.py", line 300, in once
    b = self.sock.recv(self.reading_buffer_size)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/gevent/_socket3.py", line 280, in recv
    return _socket.socket.recv(self._sock, *args)
OSError: [Errno 9] Bad file descriptor
```

Not sure if this is a problem with ws4py or gevent

**Comment by kolis** [comment] 2015-08-13 11:43
I have verified same problem in Ubuntu linux.

**Comment by sysnux** [comment] 2015-11-18 17:22
I think the problem is not related to Python3 (I have the same problem on Python-2.7), but a change in gevent-1.1a1:
       When the *handle* function returns from processing a connection,
       the client socket will be closed. This resolves the non-deterministic
       closing of the socket, fixing ResourceWarnings under Python 3 and PyPy

Commenting out line 155 of gevent/baseserver.py (on gevent-1.1rc1) solves the error for me, but I don't know how to properly fix this issue.

**Comment by hyt-hz** [comment] 2015-12-15 07:29
Please check the pull request #180

**Comment by tito** [comment] 2017-03-24 15:58
Works in master!

**Closed by tito** 2017-03-24 15:58 UTC
