### ISSUE TITLE
wss is always one message behind

### ISSUE THREAD

**Issue by zackgalbreath** [Lawouach/WebSocket-for-Python#128] opened 2014-04-11 20:33 UTC
Messages sent over wss are not received by the server until a subsequent message is sent.  In other words, the server is always one message behind the client.  This only happens over wss, not ws.

Here are the steps to reproduce this issue:
1. python echo_cherrypy_server.py --ssl
2. navigate to https://127.0.0.1:9000 in a web browser
3. notice that no message ("Userxx entered the room") appears in the chat room.
4. type anything into the input box and click Send.  Your new message won't appear, but you will now see the previous one informing you that you entered the room.

I used Firefox and Chrome on Mac & Ubuntu to test this issue.  This behavior did not vary.

**Comment by nicklasb** [comment] 2015-05-06 22:41
FYI, this still seems to be an issue. 

I resorted to always sending an empty packet just to make stuff work during early development. But in production, this is a bit too ugly as somebody just might fix that bug one day.

As SSL seems like something quite important to support, I would therefore designate this one as pretty serious. 

Has anyone made an upstream bug report, or could @zackgalbreath 's workaround be improved upon so that could even be included in the library?

**Comment by sunng87** [comment] 2015-08-11 08:13
I can reproduce this issue too. I need to send one more packet in order to receive a previous one.

And there's no cherrypy in my stack. My server in powered by Java and it works OK with other clients. So I think this should be an issue of ws4py.

**Comment by Lawouach** [comment] 2015-08-11 08:16
Hi,

are you using websocket over SSL?

**Comment by sunng87** [comment] 2015-08-11 08:25
@Lawouach yes, this issue only happens on SSL. It works great on plain socket.

**Comment by Lawouach** [comment] 2015-08-11 08:29
Thanks. I'll try to see what I can find.

**Comment by sunng87** [comment] 2015-08-11 08:43
Thanks!

**Comment by ronin8600** [comment] 2016-01-27 01:38
Is there an update on this?  I'm having the same issue.

**Comment by nicklasb** [comment] 2016-01-27 01:43
I think this was addressed in #167.

**Comment by ronin8600** [comment] 2016-01-27 02:11
Thank you!!

**Comment by tito** [comment] 2017-03-23 23:02
Fixed in #167 by https://github.com/Lawouach/WebSocket-for-Python/commit/75b88bdecd988694b0429c46cf5c3d6c719cc1f2#diff-9d928fbc7f89aae0cf0407d407b71841R316

**Closed by tito** 2017-03-23 23:02 UTC
